Machine.add(me.dir()+"/Bot.ck");
Machine.add(me.dir()+"/MahaDevi.ck");
Machine.add(me.dir()+"/GanaPati.ck");
Machine.add(me.dir()+"/BreakBot.ck");
Machine.add(me.dir()+"/Clappers.ck");
Machine.add(me.dir()+"/JackGuitar.ck");
Machine.add(me.dir()+"/JackBass.ck");
Machine.add(me.dir()+"/JackPerc.ck");
Machine.add(me.dir()+"/server.ck");
Machine.add(me.dir() + "/wireless.ck");
